import { Dimensions, Platform, StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.background },
    header: {
        backgroundColor: COLORS.primary,
        paddingTop: Platform.OS === 'ios' ? 50 : 20,
        paddingBottom: 16,
        paddingHorizontal: 20,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        zIndex: 10,
    },
    headerLeft: { flex: 1 },
    collegeName: { color: '#fff', fontSize: 20, fontWeight: 'bold' },
    tagline: { color: 'rgba(255,255,255,0.7)', fontSize: 12, marginTop: 2 },
    logoutBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.15)', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 10 },
    logoutText: { color: '#fff', marginLeft: 6, fontWeight: '600', fontSize: 13 },
    mainContent: { flex: 1, flexDirection: 'row' },
    sidebar: {
        width: Dimensions.get('window').width > 800 ? 220 : '85%',
        backgroundColor: COLORS.white,
        borderRightWidth: 1,
        borderRightColor: COLORS.border,
        paddingVertical: 16,
    },
    sidebarItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 16,
        marginBottom: 4,
        marginHorizontal: 8,
        borderRadius: 12,
    },
    sidebarItemActive: {
        backgroundColor: COLORS.primary,
    },
    sidebarText: { marginLeft: 14, fontSize: 14, color: COLORS.textSecondary, fontWeight: '500' },
    sidebarTextActive: { color: COLORS.white, fontWeight: '600' },
    contentArea: { flex: 1, backgroundColor: COLORS.background },
    filterContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        padding: 12,
        backgroundColor: COLORS.white,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.border,
        alignItems: 'center',
        gap: 12,
    },

    filterItem: { flexDirection: 'row', alignItems: 'center' },
    filterLabel: { fontSize: 12, fontWeight: '600', marginRight: 8, color: COLORS.textSecondary },
    pickerWrapper: {
        borderWidth: 1,
        borderColor: COLORS.border,
        borderRadius: 10,
        backgroundColor: COLORS.background,
        height: 38,
        justifyContent: 'center',
        width: 130,
    },
    picker: { height: 38, width: '100%', fontSize: 13 },
    scrollContent: { padding: 20 },
    moduleCard: {
        backgroundColor: COLORS.white,
        borderRadius: 16,
        padding: 20,
        shadowColor: COLORS.shadow,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 1,
        shadowRadius: 12,
        elevation: 3,
        marginBottom: 20,
    },
    moduleHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
    moduleTitle: { fontSize: 18, fontWeight: 'bold', color: COLORS.text },
    refreshBtn: { padding: 8, borderRadius: 8, backgroundColor: COLORS.primary + '10' },
    actionBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.primary, paddingHorizontal: 16, paddingVertical: 10, borderRadius: 10 },
    actionBtnText: { color: '#fff', marginLeft: 8, fontWeight: '600', fontSize: 13 },
    table: { marginTop: 10 },
    tableRow: { flexDirection: 'row', paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: COLORS.borderLight, alignItems: 'center' },
    tableHeader: { backgroundColor: COLORS.background, borderTopWidth: 1, borderTopColor: COLORS.border },
    tableCell: { fontSize: 13, color: COLORS.text, paddingHorizontal: 6 },
    helperText: { fontSize: 13, color: COLORS.textSecondary, marginBottom: 15 },
    editIcon: { padding: 5 },
    statsRow: { flexDirection: 'row', gap: 12, marginBottom: 20 },
    statCard: { flex: 1, backgroundColor: COLORS.white, padding: 16, borderRadius: 14, shadowColor: COLORS.shadow, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 1, shadowRadius: 8, elevation: 2 },
    statLabel: { fontSize: 12, color: COLORS.textSecondary, marginBottom: 6 },
    statValue: { fontSize: 22, fontWeight: 'bold', color: COLORS.text },
    modalOverlay: { flex: 1, backgroundColor: COLORS.overlay, justifyContent: 'center', alignItems: 'center' },
    modalBody: { backgroundColor: COLORS.white, width: '90%', maxWidth: 420, borderRadius: 20, padding: 24 },
    modalTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 16, color: COLORS.text, textAlign: 'center' },
    modalContent: { backgroundColor: COLORS.white, width: '90%', maxWidth: 420, borderRadius: 20, padding: 24 },
    label: { fontSize: 13, fontWeight: 'bold', color: COLORS.text, marginBottom: 8, marginTop: 10 },
    btnRow: { flexDirection: 'row', gap: 12, marginTop: 20 },
    input: { borderWidth: 1.5, borderColor: COLORS.border, borderRadius: 10, padding: 12, marginBottom: 14, fontSize: 14, backgroundColor: COLORS.background },
    row: { flexDirection: 'row', gap: 12 },
    btn: { flex: 1, padding: 14, borderRadius: 10, alignItems: 'center', justifyContent: 'center', flexDirection: 'row' },
    cancelBtn: { backgroundColor: COLORS.background, borderWidth: 1, borderColor: COLORS.border },
    saveBtn: { backgroundColor: COLORS.primary },
    smallInput: {
        borderWidth: 1.5,
        borderColor: COLORS.border,
        borderRadius: 8,
        padding: 8,
        fontSize: 12,
        textAlign: 'center',
        backgroundColor: COLORS.white,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.border,
        paddingBottom: 12,
    },
    detailSection: {
        marginBottom: 20,
        padding: 16,
        backgroundColor: COLORS.background,
        borderRadius: 14,
    },
    sectionTitle: {
        fontSize: 15,
        fontWeight: 'bold',
        color: COLORS.primary,
        marginBottom: 14,
        borderLeftWidth: 3,
        borderLeftColor: COLORS.primary,
        paddingLeft: 10,
    },
    detailGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    detailLabel: {
        fontSize: 12,
        color: COLORS.textSecondary,
        marginBottom: 3,
    },
    detailValue: {
        fontSize: 14,
        color: COLORS.text,
        fontWeight: '500',
    },
    btnText: {
        color: COLORS.white,
        fontWeight: '600',
        fontSize: 14,
    },
    checkboxContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.borderLight,
    },
    checkboxLabel: {
        marginLeft: 12,
        fontSize: 14,
        color: COLORS.text,
    },
    // GFM Action Dashboard Styles
    smallStatusBtn: {
        flex: 1,
        height: 30,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: COLORS.border,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.background,
    },
    smallStatusText: {
        fontSize: 12,
        fontWeight: 'bold',
        color: COLORS.textLight,
    },
    // Admin Reports & Audit Styles
    reportSessionCard: {
        backgroundColor: COLORS.background,
        borderRadius: 12,
        padding: 15,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    sessionMeta: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.borderLight,
    },
    sessionMetaText: {
        fontSize: 12,
        color: COLORS.text,
    },
    auditContainer: {
        marginTop: 5,
    },
    auditItem: {
        flexDirection: 'row',
        gap: 10,
        marginBottom: 8,
        paddingRight: 10,
    },
    auditText: {
        fontSize: 11,
        color: COLORS.text,
        flex: 1,
        lineHeight: 16,
    },
    toggleGroup: {
        flexDirection: 'row',
        backgroundColor: COLORS.background,
        borderRadius: 10,
        padding: 4,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    toggleBtn: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 7,
    },
    toggleBtnActive: {
        backgroundColor: COLORS.white,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    toggleText: {
        fontSize: 12,
        color: COLORS.textLight,
        fontWeight: '600',
    },
    toggleTextActive: {
        color: COLORS.primary,
    },
    moduleSwitchBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        borderRadius: 10,
        backgroundColor: 'rgba(255,255,255,0.05)',
    },
    moduleSwitchBtnActive: {
        backgroundColor: COLORS.primary,
    },
    moduleSwitchText: {
        marginLeft: 10,
        fontSize: 14,
        fontWeight: 'bold',
        color: COLORS.textLight,
    },
    moduleSwitchTextActive: {
        color: '#fff',
    },
    searchSuggestionsBox: {
        position: 'absolute',
        top: 45,
        left: 0,
        right: 0,
        backgroundColor: COLORS.white,
        borderRadius: 12,
        shadowColor: COLORS.shadow,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 1,
        shadowRadius: 20,
        elevation: 10,
        borderWidth: 1,
        borderColor: COLORS.borderLight,
        paddingVertical: 5,
        zIndex: 9999,
    },
    searchSuggestionItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.borderLight,
    },
    suggestionName: {
        fontSize: 14,
        fontWeight: 'bold',
        color: COLORS.text,
    },
    suggestionSub: {
        fontSize: 11,
        color: COLORS.textSecondary,
        marginTop: 2,
    },
    absentRollsText: {
        fontSize: 14,
        color: COLORS.error,
        fontWeight: 'bold',
        marginLeft: 5,
    },
    attendanceSummaryCard: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 15,
        marginBottom: 20,
        elevation: 2,
        borderWidth: 1,
        borderColor: '#eee',
    },
    summaryRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginBottom: 15,
    },
    summaryItem: {
        alignItems: 'center',
    },
    summaryLabel: {
        fontSize: 12,
        color: COLORS.textLight,
        marginBottom: 2,
    },
    summaryValue: {
        fontSize: 18,
        fontWeight: 'bold',
        color: COLORS.text,
    },
    absentRollsRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
        alignItems: 'center',
    },
    absentRollsLabel: {
        fontSize: 13,
        color: COLORS.textLight,
        fontWeight: '600',
    },
    emptyText: {
        fontSize: 16,
        color: COLORS.textLight,
        marginTop: 15,
        marginBottom: 5,
        textAlign: 'center'
    },
});
